services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: ./Nieuwsbrief/Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
